### PR TITLE
Use openssl with reqwest for now

### PR DESCRIPTION
**Pull request by matthauck**

### CODE REVIEW

**Comment by matthauck** [comment]
Was trying to upgrade to latest things but ran into troubles running reqwest from tokio threads, which is a no-no. Trying another route: use openssl instead of rustls to fix the problem mentioned in #233.

**Comment by connyay** [comment]
Why did we use `rustls-tls` initially?

**Comment by matthauck** [comment]
there may have been conflicts with different versions of openssl-sys maybe? i don't quite remember.

**Comment by jmealins** [comment]
reqwest? hilarious

**Pull request merged**
