### PR TITLE
Support LDAP login

### PR DESCRIPTION
**Pull request by matthauck**

### CODE REVIEW

**Comment by octobot-tanium** [comment]
Force-push detected: before: 0e58efa, after: 0e7e55c: Identical diff post-rebase

**Comment by briangreenery** [comment]
Do certificates or trust need to be configured for this?

**Comment by briangreenery** [comment]
Still not sure how this ensures that the LDAP server is trusted.

**Comment by jmealins** [comment]
I guess the only way you can trust is via configuration i.e. ldaps:// I am not sure there is a way to pin a certificate for a ldaps server.

**Comment by matthauck** [comment]
The `ldap3` crate doesn't have a way of disabling SSL verification it claims. I believe it uses the system certificate store. Adding the right certs into docker may be a tricky task...

**Comment by jmealins** [comment]
would it be as simple as specifying a ca-certificates bundle? or adding to it?

**Pull request merged**
