### PR TITLE
Updating libraries to latest versions

### PR DESCRIPTION
**Pull request by matthauck**
Whew. Looks like tokio and hyper had quite a big API change in the
latest version.

No longer pass around a reactor Remote to construct a HTTPClient.
Instead it uses `tokio::spawn` to submit tasks to the context-relevant
event loop. One offshoot of this was that `server::main::start`
needed to be run inside the event loop.

### CODE REVIEW

**Comment by matthauck** [comment]
Diff looks huge, but most of it is Cargo.lock changes and mostly unsubstantial changes. 

Biggest change really is interaction with the tokio reactor...

**Comment by jmealins** [comment]
looks like mostly syntax plus REMOTE to nada changes?

**Comment by matthauck** [comment]
hah. jinx.

**Comment by matthauck** [comment]
_tacobot-tuesday!_

**Pull request merged**
